version: "3"
services:
  #Redis
  redis:
    image: redis:alpine
    container_name: redis

  # Database Postgres
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_BD=postgres1
      - POSTGRES_USER=postgres1
      - POSTGRES_PASSWORD=postgres1
    container_name: postgres_db

  #Django App
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  #celery
  celery:
    restart: always
    build:
      context: .
    command: celery -A dockerdjango worker -l INFO
    volumes:
      - .:/django
    container_name: celery
    depends_on:
      - db
      - redis
      - app

  